name: Deploy all Lambda functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # --- video_transcriber ---
      - name: Deploy video_transcriber
        run: |
          cd video_transcriber/lambda
          mkdir -p package
          cp lambda_function.py package/
          cd package
          python -m pip install -r requirements.txt -t .
          zip -r ../function.zip .
          cd ..
          aws lambda update-function-code \
            --function-name video_transcriver \
            --zip-file fileb://function.zip
            